### PR TITLE
Upgrade markdown-it to 12.3.2

### LINKED ISSUE #31: [SECURITY UPDATE] Uncontrolled Resource Consumption in markdown-it
Hello,

the `npm install jstransformer-markdown-it`  shows the warning:

```
 severity vulnerabilities
```

the `npm audit` shows:

```
# npm audit report

markdown-it  <12.3.2
Severity: moderate
Uncontrolled Resource Consumption in markdown-it - https://github.com/advisories/GHSA-6vfc-qv3f-vr6c
No fix available
node_modules/markdown-it
  jstransformer-markdown-it  *
  Depends on vulnerable versions of markdown-it
  node_modules/jstransformer-markdown-it

2 moderate severity vulnerabilities

Some issues need review, and may require choosing a different dependency.
```

Can you please update the `markdown-it` to newest version?

### PR DESCRIPTION
**Pull request by shakeelmohamed**
This dependency update addresses the following security vulnerability: https://github.com/advisories/GHSA-6vfc-qv3f-vr6c

The test run passed, and I didn’t see any regressions in my quick tests.
In particular, this has been the only vulnerability in a few of my projects 😄 

Let me know if there’s anything I can to do help move this along.

Closes #31.

### CODE REVIEW

**Comment by argoroots** [comment]
Is there a plan to make release with this fix?

**Comment by rriemann** [comment]
Please make it happen!

**Comment by Zearin** [comment]
The latest version of `markdown-it` is now **13.0.1**.

**Comment by Zearin** [comment]
@RobLoach : Can you please consider merging this PR (or requesting an update so that it uses `markdown-it >= 13`?  

This will resolve a moderate security issue raised by `npm audit` about this jstransformer package.

**Comment by dennisreimann** [comment]
@RobLoach Can you do a new release with this one merged? It'll allow projects that use jstransformer-markdown-it as a dependency to get rid of the vulnerability.

I also wouldn't mind it using markdown-it v13.

**Pull request merged**
